//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityManager.Service.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CharityEntities : DbContext
    {
        public CharityEntities()
            : base("name=CharityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackageItem> PackageItems { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Patron> Patrons { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<Introducer> Introducers { get; set; }
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Research> Researches { get; set; }
        public virtual DbSet<ManagerViewpoint> ManagerViewpoints { get; set; }
    }
}
