//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityManager.Service.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public int ID { get; set; }
        public int PatronID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<short> EmploymentStatus { get; set; }
        public Nullable<int> Income { get; set; }
        public Nullable<int> RelationEntityID { get; set; }
        public Nullable<short> EducationStatus { get; set; }
        public int EducationEntityID { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool Active { get; set; }
    
        public virtual Patron Patron { get; set; }
    }
}
