//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityManager.Service.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerViewpoint
    {
        public int ID { get; set; }
        public int RequestID { get; set; }
        public Nullable<byte> ViewPoint { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyUser { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
