//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityManager.Service.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageItem
    {
        public int ID { get; set; }
        public int PackageID { get; set; }
        public Nullable<int> TypeEntityID { get; set; }
        public Nullable<long> Amount { get; set; }
        public string Title { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public bool Active { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
